openapi: 3.1.0
info:
  title: migue.ai API
  version: 1.0.0
paths:
  /webhook:
    get:
      summary: Verify WhatsApp webhook
      parameters:
        - in: query
          name: hub.mode
          schema: { type: string }
        - in: query
          name: hub.verify_token
          schema: { type: string }
        - in: query
          name: hub.challenge
          schema: { type: string }
      responses:
        '200': { description: OK }
        '403': { description: Forbidden }
    post:
      summary: Receive WhatsApp events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200': { description: OK }
        '400': { description: Bad Request }
        '401': { description: Invalid signature }
        '405': { description: Method Not Allowed }


